apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      scheduler: lvm-scheduler
      containers:
      - name: nginx
        image: uhub.ucloud.cn/pingcap/nginx:1.11-alpine
        resources:
          limits:
            pingcap.com/loopback-disk: 30M
          requests:
            pingcap.com/loopback-disk: 30M
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: lvm-volume-provisioner
      resources:
        requests:
          storage: 30M
